//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTag
    {
        public int QuestionTagID { get; set; }
        public int QuestionID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> SubTopicID { get; set; }
        public Nullable<int> LearningObjectiveID { get; set; }
        public Nullable<int> LearningOutcomeID { get; set; }
        public Nullable<int> LearningLevelID { get; set; }
        public Nullable<int> DifficultyLevelID { get; set; }
        public int CompetencyID { get; set; }
        public Nullable<int> SkillID { get; set; }
        public Nullable<int> SubskillID { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual Competency Competency { get; set; }
        public virtual Course Course { get; set; }
        public virtual DifficultyLevel DifficultyLevel { get; set; }
        public virtual LearningLevel LearningLevel { get; set; }
        public virtual LearningObjective LearningObjective { get; set; }
        public virtual LearningOutcome LearningOutcome { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual SubSkill SubSkill { get; set; }
        public virtual SubTopic SubTopic { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
