//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOption
    {
        public int QuestionOptionID { get; set; }
        public int QuestionID { get; set; }
        public string OptionID { get; set; }
        public string OptionText { get; set; }
        public bool CorrectOption { get; set; }
        public string OptionHint { get; set; }
        public string ExplanationForOption { get; set; }
        public Nullable<int> MisconceptionID { get; set; }
        public Nullable<int> OtherMisconceptionID1 { get; set; }
        public Nullable<int> OtherMisconceptionID2 { get; set; }
        public Nullable<int> ScoringWeight { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Misconception Misconception { get; set; }
        public virtual Misconception Misconception1 { get; set; }
        public virtual Misconception Misconception2 { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
