//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultDetail
    {
        public int TestResultDetailID { get; set; }
        public int TestCycleID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public int TestPaperID { get; set; }
        public int UserID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> QuestionSequence { get; set; }
        public string CorrectOption { get; set; }
        public string Attempted { get; set; }
        public string UserOption { get; set; }
        public Nullable<decimal> MarksObtained { get; set; }
        public Nullable<int> ScoringWeight { get; set; }
        public Nullable<decimal> TimeTaken { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> ScaledScore { get; set; }
    
        public virtual TestCycle TestCycle { get; set; }
        public virtual TestPaper TestPaper { get; set; }
        public virtual School School { get; set; }
        public virtual User User { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
