//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestPaper()
        {
            this.TestPaperSections = new HashSet<TestPaperSection>();
            this.TestPaperSectionQuestions = new HashSet<TestPaperSectionQuestion>();
            this.TestResults = new HashSet<TestResult>();
            this.TestResultDetails = new HashSet<TestResultDetail>();
        }
    
        public int TestPaperID { get; set; }
        public string TestPaperCode { get; set; }
        public string ISBN { get; set; }
        public string Description { get; set; }
        public string Instructions { get; set; }
        public string TestPaperSetCode { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int MaxQuestions { get; set; }
        public decimal Time { get; set; }
        public decimal Marks { get; set; }
        public int CourseID { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual TestPaperSet TestPaperSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestPaperSection> TestPaperSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestPaperSectionQuestion> TestPaperSectionQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResultDetail> TestResultDetails { get; set; }
    }
}
