//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMapping
    {
        public int UserMappingID { get; set; }
        public int UserID { get; set; }
        public int SchoolID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string SectionID { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string AdmissionNo { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual School School { get; set; }
        public virtual User User { get; set; }
    }
}
